# Theme settings
doks:
    baseurl:
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Bojler
            image:
        nav:
    footer:
        content:
            logo:
                text: Bojler
                image:
            copyright: Bojler is an CSS email framework for developing responsive and lightweight email templates that will render correctly across each of the most popular email clients.
        social_list:
            - network_name: facebook
              profile_url: https://www.facebook.com/Slicejack/
            - network_name: twitter
              profile_url: https://twitter.com/slicejack
            - network_name: instagram
              profile_url: https://www.instagram.com/slicejack/
            - network_name: linkedin
              profile_url: https://www.linkedin.com/company-beta/278978/
            - network_name: github
              profile_url: https://github.com/Slicejack
    google_analytics:
        tracking_code: UA-7374079-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
